# Generated by Django 3.2.5 on 2021-09-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='extra',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
