# Generated by Django 3.2.5 on 2022-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbookingreview_usersitereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingreview',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.astrologybooking'),
        ),
        migrations.AlterField(
            model_name='userbookingreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='usersitereview',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
