# Generated by Django 3.2.5 on 2021-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paygw_order',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
