# Generated by Django 3.2.5 on 2021-08-13 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_gstpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Field ignored if user_specific is checked.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user_specific',
            field=models.BooleanField(default=True, help_text='This will allow only a specific user to access the coupon code.'),
        ),
    ]
