# Generated by Django 3.2.5 on 2021-08-21 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_auto_20210813_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='plan',
            field=models.CharField(blank=True, choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '60 minutes')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='plan_specific',
            field=models.BooleanField(default=False, help_text='This will allow coupon to be applied on specific Plan.'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.coupon')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
