# Generated by Django 3.2.5 on 2021-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20210821_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='plan',
            field=models.IntegerField(blank=True, choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '60 minutes')], max_length=1, null=True),
        ),
    ]
