# Generated by Django 3.2.5 on 2021-09-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_extra'),
        ('billing', '0007_wallet_walletinvoice_wallettxn'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inr_amount', models.IntegerField(default=0)),
                ('cashback_percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('F', 'Flat Discount'), ('P', 'Percentage Discount')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='astrologybooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Field ignored if user_specific is checked.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
