# Generated by Django 3.2.5 on 2021-09-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20210925_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologybooking',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.walletinvoice'),
        ),
    ]
