# Generated by Django 3.2.5 on 2021-09-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_astrologybooking_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponusage',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.walletinvoice'),
        ),
    ]
