# Generated by Django 3.2.5 on 2021-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_wallettxn_txn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettxn',
            name='txn_amount_sans_tax',
            field=models.FloatField(default=0),
        ),
    ]
