# Generated by Django 3.2.5 on 2022-01-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210928_1503'),
        ('billing', '0013_wallettxn_txn_amount_sans_tax'),
    ]
