# Generated by Django 3.2.5 on 2022-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220203_1924'),
        ('billing', '0014_auto_20220107_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPlanUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.walletinvoice')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.walletplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
