# Generated by Django 3.2.5 on 2022-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_walletplanusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletplan',
            name='single_use',
            field=models.BooleanField(default=False),
        ),
    ]
