# Generated by Django 3.2.5 on 2022-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aouth', '0006_auto_20210914_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
