"""
Django settings for astrothought project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import datetime
from pathlib import Path
import firebase_admin


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y@xyo15s2ihcqd4f^w7j^tkuphe#k0(av=^egpw#oi=7^lkvpt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DEPLOYED_HOST = 'astro-apis.dev.greybits.in'
ALLOWED_HOSTS = ['localhost', '127.0.0.1',
                 'astro-apis.dev.greybits.in', 'v2.apis.astrothought.com', 'spirico.life']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'aouth',
    'astrologer',
    'horoscope',
    'billing',
    'users',
    'django_crontab',
    'django_rest_passwordreset',
    'django_filters'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'astrothought.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'astrothought.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'at_v3',
        'USER': 'webmaster',
        'PASSWORD': 'B#QHD9oFkxNW',
        'HOST': 'prod.db.svc.astrothought.com',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
# #STATICFILES_DIRS = (
# #  '/static/',
# #)
STATIC_URL = '/static/'

STATICFILES_DIRS = (
           os.path.join(BASE_DIR, "static"),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'aouth.CustomUser'


# Email SMTP Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'in-v3.mailjet.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'da0a609ffb8533c7ddc8da178d810547'
EMAIL_HOST_PASSWORD = '81c44a7071d9bdb02e80ef905aaf675c'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

# RazorPay Keys
# https://dashboard.razorpay.com/app/keys
RZPAY_AUTH = ('rzp_live_KqEg03ZdEks1b7', 'Gg14ImyR3KcQ9VFlrroaleDy')
# RZPAY_AUTH = ('rzp_test_63jt4p38gLz6G8', 'GJUzueUIe9LWuR5J8jThWyrS')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=20),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=30)
}

CRONJOBS = [
    ('* * * * *', 'users.cron.trigger'),
    ('0 0 1 * *', 'users.cron.monthly_invoice_generator')
]


# AWS Credentials
# --
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""


# Celery Config
# --
CELERY_accept_content = ['application/json']
CELERY_task_serializer = 'json'
CELERY_TASK_DEFAULT_QUEUE = 'django-myqueue'
BROKER_URL = "sqs://%s:%s@" % (AWS_ACCESS_KEY_ID,
                                      AWS_SECRET_ACCESS_KEY)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "region": "ap-southeast-1",
    'visibility_timeout': 7200,
    'polling_interval': 1
}
CELERY_result_backend = None


# Django-rest-passwordreset Config
# --
DJANGO_REST_MULTITOKENAUTH_RESET_TOKEN_EXPIRY_TIME = 1
DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAGE = False


# Firebase admin SDK app
# --
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/home/ubuntu/firebase-secret.json"
firebase_admin.initialize_app()
