# Generated by Django 3.2.5 on 2021-07-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Astrologer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.FloatField()),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField()),
                ('verified', models.BooleanField()),
                ('penalized', models.BooleanField()),
                ('avatar', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('about', models.CharField(max_length=1000)),
                ('availibility_start', models.TimeField()),
                ('availibility_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('expertise', models.ManyToManyField(blank=True, to='astrologer.Expertise')),
                ('language', models.ManyToManyField(blank=True, to='astrologer.Language')),
            ],
        ),
    ]
