# Generated by Django 3.2.5 on 2021-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=13),
            preserve_default=False,
        ),
    ]
