# Generated by Django 3.2.5 on 2021-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0002_astrologer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
