# Generated by Django 3.2.5 on 2021-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0003_astrologer_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astrologer',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='astrologer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='astrologer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='astrologer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='astrologer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='astrologer',
            name='verified',
        ),
        migrations.AddField(
            model_name='astrologer',
            name='about_seo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='astrologer',
            name='title_seo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='astrologer',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
