# Generated by Django 3.2.5 on 2021-09-24 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrologer', '0004_auto_20210914_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='aouth.customuser'),
            preserve_default=False,
        ),
    ]
