# Generated by Django 3.2.5 on 2022-04-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
