name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            source venv/bin/activate
            cd v2-astro-apis
            git stash
            git pull origin main
            pip install -r requirements.txt
            sudo service astrothought-v2 restart
            deactivate
            echo "Deployment successful to Production API Server on AWS"
